name: innbucks
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  get: ^4.6.6
  image_picker: ^1.1.2
  http: ^1.2.2
  connectivity_plus: ^2.3.8
  dio: ^5.7.0
  shimmer: ^3.0.0
  device_preview: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/language/
    - assets/images/icons/
    - assets/images/logo/
    - assets/images/billboads/
    - assets/icon/
    - assets/demo_images/
    - assets/logo/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900